openapi: "3.0.0"
info:
  title: sampleapi
  description: 開発のサンプルです
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: ローカルの開発用サーバー
paths:
  /users:
    get:
      summary: Get all users.
      description: Returns an array of User model
      responses:
        '200':
          description: A JSON array of User model
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
    post:
      summary: Create a new User
      description: Create a new User
      requestBody:
        description: user to create
        content:
          application/json:
            schema: # POSTするオブジェクト
              $ref: '#/components/schemas/User'
            example:
              id:
              name: post_user
      responses:
        '201':
          description: CREATED
components:
  schemas: # スキーマオブジェクトの定義
    User: # モデル名
      type: object
      required: # 必須フィールド
        - id
      properties:
        id:
          type: integer
        name:
          type: string
